Added .doctrine-project.json
doctrine/DoctrineORMModule pull request #631
Opened 2020-10-31 21:16 UTC by TomHAnderson

2020-10-31 21:17 UTC, TomHAnderson commented
I believe with this PR it is time to drop the master branch.

2020-10-31 22:01 UTC, SenseException requested changes
Are `feature/drop_php5.6` and `feature/stable-doctrine-module` relevant for the documentation?

2020-10-31 22:01 UTC, SenseException commented on .doctrine-project.json
> +        "3.x"
AFAIK you don't need this one if it is the same value as the slug.

2020-10-31 22:01 UTC, SenseException commented on .doctrine-project.json
> +      ]
```suggestion
      "name":"1.x",
      "branchName":"release/1.x",
      "slug":"1.x",
      "maintained":false
```

2020-11-01 10:15 UTC, greg0ire approved these changes

2020-11-01 19:02 UTC, SenseException commented
@TomHAnderson Do you want to keep name and slug on `release/1.x`?

2020-11-01 20:10 UTC, TomHAnderson commented
@SenseException I don't understand a reason not to keep `release/1.x` as-is.  Are you suggesting removing those properties and just leaving branchName and maintined?

2020-11-01 20:15 UTC, SenseException commented
It would affect the rendering of namings on the website. It's a cosmetic change, not a technical one.

2020-11-01 20:16 UTC, greg0ire commented
I think @SenseException was suggesting using `1.x` as name and slug, and drop the `release/` part.

2020-11-01 20:40 UTC, TomHAnderson commented
Thanks you two.  I've simplified the name and slug to `1.x`

2020-11-01 20:51 UTC, merged