Hotfix/migrations object manager
doctrine/DoctrineORMModule pull request #640
Opened 2020-11-16 10:31 UTC by TomHAnderson

2020-11-16 20:15 UTC, SenseException requested changes
Any update in the composer.json also needs to be done in composer-no-optional-repos.json for any future changes in the dependencies. This might lead to issues in the future. What about doing a `composer remove` for the optional parts?

2020-11-16 20:15 UTC, SenseException commented on test/DoctrineORMModuleTest/Console/Helper/MigrationsConfigurationHelperTest.php
> +        if (! class_exists(VersionCommand::class)) {
Every test has this check in this class. Does it make sense to put it into `setUp()`?

2020-11-17 04:58 UTC, TomHAnderson commented on test/DoctrineORMModuleTest/Console/Helper/MigrationsConfigurationHelperTest.php
> +        if (! class_exists(VersionCommand::class)) {
Done though `setUp()` is an odd place to call a function acting on a test.

2020-11-17 04:59 UTC, TomHAnderson commented
> Any update in the composer.json also needs to be done in composer-no-optional-repos.json for any future changes in the dependencies. This might lead to issues in the future. What about doing a `composer remove` for the optional parts?

I've done this and it is more simple this way.  Please see the `.travis.yml` file

2020-11-17 17:43 UTC, SenseException commented on test/DoctrineORMModuleTest/Console/Helper/MigrationsConfigurationHelperTest.php
> +        if (! class_exists(VersionCommand::class)) {
Only if really every test case in `MigrationsConfigurationHelperTest`  is affected.

2020-11-17 17:43 UTC, SenseException approved these changes

2020-11-17 22:32 UTC, greg0ire approved these changes

2020-11-17 22:33 UTC, merged