Add support for persistence 2.0
doctrine/DoctrineORMModule pull request #644
Opened 2020-12-06 22:46 UTC by TomHAnderson

2020-12-07 09:46 UTC, driehle requested changes

2020-12-07 09:46 UTC, driehle commented on composer.json
> +        "doctrine/persistence":                 "^1.3.3|^2.0",
@TomHAnderson Looks good to me, but I am unsure why you are requiring doctrine/persistance ^1.3.3. The forward compatibility has been added with 1.3.0 already, see https://github.com/doctrine/persistence/tree/1.3.0/lib/Doctrine. Besides, according to https://getcomposer.org/doc/articles/versions.md#version-range you should the a double pipe.

```suggestion
        "doctrine/persistence":                 "^1.3 || ^2.0",
```

2021-01-07 21:19 UTC, SenseException commented
Looks like the CS fixes are the last step before this can be approved.

2021-01-07 21:58 UTC, greg0ire commented
Also, the "Trigger Travis" commit can be dropped haha

2021-01-07 22:03 UTC, greg0ire commented
Ah this is missing some autoload calls, I will add them.

2021-01-07 22:07 UTC, greg0ire commented
It was just one call actually, done.

2021-01-07 22:07 UTC, greg0ire approved these changes

2021-01-08 03:22 UTC, TomHAnderson commented
> Looks like the CS fixes are the last step before this can be approved.

Yup.  Those are done now if you're ready to approve it

2021-01-08 08:29 UTC, greg0ire commented
@TomHAnderson please revert, the `class_exists` is intended, and should not break CS. Please read my commit message as to why this weird artefact is necessary.

2021-01-11 01:36 UTC, TomHAnderson commented
@greg0ire I restored your `class_exists` function and modified the phpcs.xml to allow for that usage.  @SenseException that fixes the cs check if I may now solicit your approval.

2021-01-11 08:04 UTC, greg0ire approved these changes

2021-01-11 20:25 UTC, SenseException approved these changes

2021-01-12 10:21 UTC, merged

2021-01-12 10:21 UTC, greg0ire commented
Thanks @TomHAnderson !