Allow config DependencyFactory
doctrine/DoctrineORMModule pull request #653
Opened 2021-01-16 16:01 UTC by fezfez

this PR allow to config DependencyFactory from config

It it useful for example to change Doctrine\Migrations\Version\Comparator strategies.

Example of usage : 

 ```php
use Doctrine\Migrations\Version\Comparator;

[
    'doctrine' => [
        'migrations_configuration' => [
            'orm_default' => [
                'dependency_factory_services' => [
                    Comparator::class => MyComparator::class
                ],
            ],
        ],
    ],
];

 ```

idea from https://github.com/doctrine/migrations/issues/1074

2021-01-29 18:47 UTC, fezfez commented
Ping! 🙃

2021-01-30 18:06 UTC, SenseException requested changes
Thanks for the contribution. I'd say that this should target 3.2 because it's a new feature. Yes, I know there's no branch for it yet, so you currently can't change the target branch.

Please also create a test where `dependency_factory_services` is omitted in the config.
Also, please add this new config key to the documentation and how it's used.

2021-01-30 18:06 UTC, SenseException commented on test/DoctrineORMModuleTest/Service/MigrationsCommandFactoryTest.php
> +                        ->willReturnOnConsecutiveCalls($config, $entityManager, 'test');
Does it matter that the calls are consecutive? If there is no dependency to a certain order, `willReturnValueMap()` would be a more fitting choice.

2021-02-08 19:02 UTC, fezfez commented on test/DoctrineORMModuleTest/Service/MigrationsCommandFactoryTest.php
> +                        ->willReturnOnConsecutiveCalls($config, $entityManager, 'test');
done

2021-02-08 19:02 UTC, fezfez commented
> Thanks for the contribution. I'd say that this should target 3.2 because it's a new feature. Yes, I know there's no branch for it yet, so you currently can't change the target branch.
> 
> Please also create a test where `dependency_factory_services` is omitted in the config.
> Also, please add this new config key to the documentation and how it's used.

Done, waiting for 3.2.x branch ;)

2021-02-08 23:55 UTC, TomHAnderson commented
Thank you, @fezfez, I've changed this PR to 3.2.x

2021-02-09 20:00 UTC, SenseException requested changes

2021-02-09 20:00 UTC, SenseException commented on test/DoctrineORMModuleTest/Service/MigrationsCommandFactoryTest.php
> +            ]));
```suggestion
            ->willReturnMap([
                ['config', $config],
                ['doctrine.entitymanager.orm_default', $entityManager],
                ['myService', 'test'],
            ]);
```

2021-02-09 20:00 UTC, SenseException commented on test/DoctrineORMModuleTest/Service/MigrationsCommandFactoryTest.php
> +            ]));
```suggestion
            ->willReturnMap([
                ['config', $config],
                ['doctrine.entitymanager.orm_default', $entityManager],
            ]);
```

2021-02-09 21:09 UTC, SenseException approved these changes

2021-02-09 21:10 UTC, SenseException requested changes
Too early for approval. The docs are still missing.

2021-02-10 13:43 UTC, bdudelsack commented
I would like to solve my issue with this PR: https://github.com/doctrine/DoctrineORMModule/issues/655

The Problem at the moment is that i can register my own `MigrationFactory` class, but i cannot create the original one or get it from the `DepdencencyFactory` because the Service Locator does not know anything about it.

2021-02-11 08:40 UTC, fezfez commented
@SenseException : i have added some docs, if your are ok with it, i will rebase the branch before merging :)

2021-02-11 22:08 UTC, SenseException requested changes

2021-02-11 22:08 UTC, SenseException commented on docs/configuration.rst
> +Note : 'youService' has to be defined in your DIC
```suggestion
                        'service_to_overwrite' => 'custom_service_id'
                    ],
                ],
            ],
        ],
    ];

Note : 'custom_service_id' has to be defined in your DIC
```

2021-02-11 22:08 UTC, SenseException commented on docs/configuration.rst
> +List of service that can be overwrite
```suggestion
This configuration allows you, for example, to define a custom version comparator

.. code:: php

    return [
        'doctrine' => [
            'configuration' => [
                'orm_default' => [
                    'dependency_factory_services' => [
                        \Doctrine\Migrations\Version\Comparator::class => MyComparator::class
                    ],
                ],
            ],
        ],
    ];

List of services that can be overwritten
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

2021-02-11 22:11 UTC, SenseException commented
Thank you for adding the docs. Just a few small changes for them and I think it will be ready for approval.

2021-02-12 10:53 UTC, fezfez commented
> Thank you for adding the docs. Just a few small changes for them and I think it will be ready for approval.

Done and it has been rebase

2021-02-12 18:42 UTC, SenseException approved these changes
Thank you @fezfez.

2021-02-12 22:49 UTC, TomHAnderson approved these changes
I think this looks good.

2021-02-12 22:51 UTC, merged