Update docs to reflect 4.0.x as the current version
doctrine/DoctrineORMModule pull request #663
Opened 2021-06-28 10:51 UTC by driehle

With the release of `4.0.0` is looks like the file `.doctrine-project.json` has not been updated accordingly. This leads to https://www.doctrine-project.org/projects/DoctrineORMModule.html showing wrong information, where the `4.0.x` series is listed as unmaintained.

This PR updates `.doctrine-project.json` to reflect that 4.0.x is the current and maintained version of this project.

2021-06-28 21:42 UTC, SenseException requested changes

2021-06-28 21:42 UTC, SenseException commented on .doctrine-project.json
>        "maintained": true
```suggestion
      "maintained": false
```

2021-06-28 21:42 UTC, SenseException commented on .doctrine-project.json
> +      "maintained": true
```suggestion
      "maintained": false
```

2021-06-28 21:42 UTC, SenseException commented on .doctrine-project.json
> +      "maintained": true
```suggestion
      "maintained": false
```

not sure about this one though.

2021-06-29 11:03 UTC, driehle commented
The Readme should probably be updated as well (i.e. remove the section about the branches)?

2021-06-29 20:24 UTC, SenseException commented
> The Readme should probably be updated as well (i.e. remove the section about the branches)?

Good catch. That would be great.

2021-06-29 21:06 UTC, TomHAnderson commented
I fixed the issues with static analysis and CI and rebased this.  Next, I edited the README.md to reflect the change in branch maintenance.

2021-06-29 21:38 UTC, SenseException approved these changes
@TomHAnderson Does .doctrine-project.json contain the correct maintained-flags for the branches?

2021-07-05 19:25 UTC, TomHAnderson commented
3.0 & 3.2 were listed as maintained but with this PR it is a good time to adjust the maintained branch to just 4.0.x in an effort to maintain only PHP 8.0 compatible branches.

2021-07-05 19:25 UTC, merged