PHP 8.2 Support
doctrine/DoctrineORMModule pull request #728
Opened 2022-12-12 15:00 UTC by rogervila

Hi,

This PR needs https://github.com/doctrine/DoctrineModule to release a 5.3.x version to support PHP 8.2

2022-12-13 20:42 UTC, driehle requested changes
Please take a look at the Github workflows and add 8.2 to continues integration and change coding standards and static analysis from 8.1 to 8.2.

2022-12-14 12:18 UTC, driehle commented on psalm.xml
> +    phpVersion="8.2"
Please drop this line, then Psalm will inflect the PHP version from `composer.json`

2022-12-14 12:45 UTC, rogervila commented
We will have to wait until https://github.com/doctrine/DoctrineModule/pull/796 is merged to get green on 8.2

2022-12-20 10:28 UTC, rogervila commented
@driehle I upgraded DoctrineModule, based on the conversation on https://github.com/doctrine/DoctrineModule/issues/798

2022-12-21 09:06 UTC, driehle commented
I think before we step deeper into the static analysis issues, it would make sense to provide a PR doing the same as in https://github.com/doctrine/DoctrineModule/pull/792. Then, we can rebase this PR and solve the remaining issues.

2022-12-22 11:42 UTC, driehle commented
@rogervila Could you please rebase on latest 5.3.x?

2022-12-23 10:34 UTC, driehle approved these changes

2022-12-23 10:34 UTC, merged