Fix schema_assets_filter configuration docs
doctrine/DoctrineORMModule pull request #731
Opened 2023-01-25 11:04 UTC by ittmann

The callable set as schemaAssetsFilter should return false for tables that you want filtered out 

See for example https://github.com/doctrine/dbal/blob/3.6.x/src/Configuration.php#L167 and https://github.com/doctrine/dbal/blob/4.0.x/src/Schema/AbstractSchemaManager.php#L204

2023-01-25 23:21 UTC, SenseException commented
A description about what to expect on true and false would be insightful. Something like "If the function returns true, then..."

2023-01-27 14:33 UTC, driehle requested changes
Yes, please add something in the writting text as well on how this filter works!

2023-02-06 09:59 UTC, DIReports commented
My intent with this PR was to fix the documentation error.
Documentation should probably be added to the [DBAL Configuration documentation](https://www.doctrine-project.org/projects/doctrine-dbal/en/current/reference/configuration.html) and/or [Configuration class](https://github.com/doctrine/dbal/blob/3.5.x/src/Configuration.php#L44)

With the latest package versions (dbal 3.5.3 and migrations 3.5.5) adding the 'migrations' table to the asset filter breaks doctrine migrations (and not adding it makes the schema-tool when run with the the "--complete" option drop the table)

2023-02-06 10:11 UTC, DIReports commented
Adding a table to the schema_asset_filter will not prevent an entity table from being created, only tables not owned by the DBAL from being dropped, I changed this in the first line.

Also I added some explanation on how the schema_assets_filter works and removed the 'migrations' table from the example as adding it to the asset filter currently breaks doctrine migrations.

2023-02-06 15:51 UTC, ittmann commented
> With the latest package versions (dbal 3.5.3 and migrations 3.5.5) adding the 'migrations' table to the asset filter breaks doctrine migrations (and not adding it makes the schema-tool when run with the the "--complete" option drop the table)

Opened issue https://github.com/doctrine/migrations/issues/1317
**Adding the migrations table to doctrine (dbal) schema assets filter breaks migrations**

2023-02-08 23:14 UTC, SenseException approved these changes

2023-06-09 00:54 UTC, TomHAnderson approved these changes

2023-06-09 00:59 UTC, TomHAnderson commented on phpstan.neon
> -        -
This was removed in https://github.com/doctrine/DoctrineORMModule/commit/7f112e995ab42203ceff3dd8bd8c12cba4c6939d

2023-06-09 01:03 UTC, merged